version: "3.3"

services:
  postgres:
    image: postgres:11.5
    hostname: postgres
    ports:
      - 5432:5432

  shelter:
    image: shelter:latest
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./shelter/
        target: /app/shelter/
    environment:
    - "PYTHONUNBUFFERED=0"
    command: bash -c "python shelter/entrypoint.py"
    restart: on-failure
    depends_on:
      - postgres
